update

tap phinze/homebrew-cask || true
tap homebrew/binary || true

# packages

install ack
install apple-gcc42
install autoconf
install automake
install boost
install ctags
install cmigemo
install elasticsearch
install freetype
install gd
install gdbm
install gettext
install ghc
install git
install glew
install glm
install gource
install graphviz
install groff
install haskell-platform
install hub
install hwloc
install iperf
install jenkins
install jpeg
install jq
install jsonpp
install libevent
install libpng
install libyaml
install lua
install lv
install maven
install ncurses
install openssl
install pcre
install phantomjs
install pkg-config
install rbenv
install ruby-build
install rxvt-unicode
install sdl
install sdl_image
install the_silver_searcher
install tig
install tmux
install tree
install vim --override-system-vi --with-lua --with-ruby --with-perl
install wget
install xz
install zsh

# casks

install brew-cask
cask install google-earth
cask install eagle
cask install coolterm
cask install licecap
cask install limechat

cleanup
