alias la='ls -al'
alias ll='ls -l'
alias l='ls'
alias rm='rm -i'
alias mv='mv -i'
alias gst='git status'
alias gdc='git diff --cached'
alias gfa='git fetch --all'
alias perldoc='perldoc -t'
alias pb='perlbrew'
alias hg='history | grep '
alias scr='screen -r'
alias -g G=' | grep '
alias -g GV=' | grep -v '
alias -g L=' | lv -c'
alias -g T=' | tail '
alias -g V="| vim -R -"
alias ki='tree -CA'
alias ack="ack -i \--pager='less \-R'"
alias ackjs='ack -t=js'
alias ag="ag -C 1 --pager='less \-R'"
alias findname='find . -name'
alias curl='curl --silent '
alias curlget='curl -O '

